services:
  - type: web
    name: parnasala-fellowship
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
